# The URL the site will be built for
base_url = "https://coolans.dev"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = false

build_search_index = true

[markdown]
highlight_code = true

# Whether external links are to be opened in a new tab
# If this is true, a `rel="noopener"` will always automatically be added for security reasons
external_links_target_blank = true

[extra]
# Put all your custom variables here
